export const UPDATE_LIST = 'UPDATE_LIST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_BRAND = 'FILTER_BRAND';
export const FILTER_PRICE = 'FILTER_PRICE';
export const FILTER_COLOR = 'FILTER_COLOR';
export const RESET_COUNT = 'RESET_COUNT';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_QUANCART = 'UPDATE_QUANCART';
export const SORT_PRICE = 'SORT_PRICE';
export const ACTIVE_PAGINATION = 'ACTIVE_PAGINATION';

